/**
 * KAS Catalogue — Demo Data
 * Used when CONFIG.DEMO_MODE is true
 */
const DEMO_PROJECTS = [
  {
    id: 'demo-1',
    name: 'Villa Thảo Điền',
    category: 'villa',
    address: 'Quận 2, TP.HCM',
    area: '500m²',
    style: 'Modern Luxury',
    year: '2025',
    description: 'Thiết kế nội thất biệt thự cao cấp phong cách hiện đại sang trọng. Không gian mở với ánh sáng tự nhiên, sử dụng vật liệu đá marble Ý và gỗ óc chó nhập khẩu. Hệ thống chiếu sáng thông minh tạo nên bầu không khí ấm áp và tinh tế.',
    coverImage: 'images/hero-bg.png',
    images: [
      'images/hero-bg.png',
      'images/demo-livingroom.png',
      'images/demo-bedroom.png',
      'images/demo-kitchen.png',
    ],
  },
  {
    id: 'demo-2',
    name: 'LỖI API GOOGLE RỒI!',
    category: 'penthouse',
    address: 'Bình Thạnh, TP.HCM',
    area: '350m²',
    style: 'Neo Classic',
    year: '2024',
    description: 'Căn Penthouse tầng cao nhất với tầm nhìn panorama toàn thành phố. Thiết kế tân cổ điển kết hợp hiện đại, sử dụng vật liệu cao cấp từ Châu Âu. Mỗi chi tiết được chăm chút tỉ mỉ, tạo nên không gian sống đẳng cấp bậc nhất.',
    coverImage: 'images/demo-livingroom.png',
    images: [
      'images/demo-livingroom.png',
      'images/hero-bg.png',
      'images/demo-kitchen.png',
      'images/demo-bedroom.png',
    ],
  },
  {
    id: 'demo-3',
    name: 'Căn hộ The Marq',
    category: 'apartment',
    address: 'Quận 1, TP.HCM',
    area: '180m²',
    style: 'Minimalist Modern',
    year: '2025',
    description: 'Căn hộ cao cấp phong cách tối giản hiện đại. Tối ưu không gian sống với gam màu trung tính và đường nét tinh gọn. Nội thất thiết kế riêng, tích hợp công nghệ smart home tiên tiến nhất.',
    coverImage: 'images/demo-bedroom.png',
    images: [
      'images/demo-bedroom.png',
      'images/demo-livingroom.png',
      'images/hero-bg.png',
      'images/demo-kitchen.png',
    ],
  },
  {
    id: 'demo-4',
    name: 'Biệt thự Vinhomes',
    category: 'villa',
    address: 'Quận 9, TP.HCM',
    area: '420m²',
    style: 'Contemporary',
    year: '2024',
    description: 'Biệt thự liền kề phong cách đương đại. Sự kết hợp giữa không gian xanh và nội thất tinh giản, tạo nên môi trường sống thư giãn và hài hòa. Vật liệu tự nhiên như gỗ, đá và kim loại được sử dụng xuyên suốt.',
    coverImage: 'images/demo-kitchen.png',
    images: [
      'images/demo-kitchen.png',
      'images/hero-bg.png',
      'images/demo-livingroom.png',
      'images/demo-bedroom.png',
    ],
  },
  {
    id: 'demo-5',
    name: 'Văn phòng Bitexco',
    category: 'office',
    address: 'Quận 1, TP.HCM',
    area: '250m²',
    style: 'Corporate Luxury',
    year: '2025',
    description: 'Thiết kế văn phòng cao cấp cho doanh nghiệp hàng đầu. Không gian làm việc mở kết hợp phòng họp sang trọng, phòng VIP và khu vực tiếp khách đẳng cấp. Thiết kế tối ưu hiệu suất làm việc và thể hiện đẳng cấp thương hiệu.',
    coverImage: 'images/demo-livingroom.png',
    images: [
      'images/demo-livingroom.png',
      'images/demo-kitchen.png',
      'images/hero-bg.png',
      'images/demo-bedroom.png',
    ],
  },
];
